"""add ats_type and ats_slug to companies

Revision ID: 5e567cb936ed
Revises: dee1928cedb9
Create Date: 2026-08-26 10:18:22.960377

"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op


revision: str = '5e567cb936ed'
down_revision: str | None = 'dee1928cedb9'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ats_type', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ats_slug', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_column('ats_slug')
        batch_op.drop_column('ats_type')

    # ### end Alembic commands ###
