"""relevance scoring columns

Revision ID: dee1928cedb9
Revises: 9fdad530fee7
Create Date: 2026-08-26 00:20:17.418678

"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op


revision: str = 'dee1928cedb9'
down_revision: str | None = '9fdad530fee7'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('audio_scope', sa.Text(), nullable=False, server_default='native')
        )

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('relevance_score', sa.Integer(), nullable=False, server_default='0')
        )
        batch_op.add_column(
            sa.Column(
                'is_audio_related', sa.Boolean(), nullable=False, server_default=sa.text('1')
            )
        )
        batch_op.create_index(batch_op.f('ix_jobs_is_audio_related'), ['is_audio_related'], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_is_audio_related'))
        batch_op.drop_column('is_audio_related')
        batch_op.drop_column('relevance_score')

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_column('audio_scope')

    # ### end Alembic commands ###
