#!/usr/bin/env python3
"""Migrate audio_companies_final.json to the new schema.

Adds:
  - source: "auto" for all existing entries (they were generated by scripts)
  - scrape_method: inferred from verification results
      - "playwright" for entries that were verified by Playwright
        (these are JS-rendered or anti-bot sites that HTTP can't handle)
      - "http" for everything else

Does NOT overwrite source if already set (preserves manual entries).
"""

import json


def main():
    with open("../data/audio_companies_final.json", "r") as f:
        data = json.load(f)

    # Load Playwright results to determine scrape_method
    try:
        with open("../data/playwright_results.json", "r") as f:
            pw_results = json.load(f)
    except FileNotFoundError:
        pw_results = {}

    # ATS domains — these have predictable HTML/API structures, HTTP is fine
    ats_domains = [
        "greenhouse", "lever.co", "workable.com", "workdayjobs",
        "myworkdayjobs", "icims.com", "jobvite.com", "smartrecruiters",
        "ashbyhq.com", "bamboohr.com/careers", "applytojob.com",
        "recruitee.com", "pinpointhq.com", "breezy.hr", "adp.com",
        "workforcenow", "taleo.net", "brassring.com", "successfactors",
        "metacareers.com", "amazon.jobs",
    ]

    for entry in data:
        # Add source field if missing
        if "source" not in entry:
            entry["source"] = "auto"

        # Add scrape_method if missing
        if "scrape_method" not in entry:
            url = entry["careers_url"].lower()
            pw = pw_results.get(entry["name"], {})
            pw_reason = pw.get("reason", "")

            # ATS platforms work fine with HTTP (they serve static HTML)
            if any(ats in url for ats in ats_domains):
                entry["scrape_method"] = "http"
            # If Playwright verified it with content_match, it likely needs JS
            elif entry["verified"] and pw_reason.startswith("content_match"):
                entry["scrape_method"] = "playwright"
            # If Playwright found an ATS redirect, the final URL is ATS (HTTP ok)
            elif entry["verified"] and pw_reason == "ats_redirect":
                entry["scrape_method"] = "http"
            # If verified but not by Playwright (was verified in earlier HTTP passes)
            elif entry["verified"] and not pw:
                entry["scrape_method"] = "http"
            # Unverified — default to http, scraper will fallback to playwright
            else:
                entry["scrape_method"] = "http"

    # Sort by name
    data.sort(key=lambda e: e["name"].lower())

    with open("../data/audio_companies_final.json", "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

    verified = sum(1 for e in data if e["verified"])
    playwright_count = sum(1 for e in data if e.get("scrape_method") == "playwright")
    http_count = sum(1 for e in data if e.get("scrape_method") == "http")

    print(f"Migrated {len(data)} entries")
    print(f"  source=auto: {sum(1 for e in data if e.get('source') == 'auto')}")
    print(f"  source=manual: {sum(1 for e in data if e.get('source') == 'manual')}")
    print(f"  scrape_method=http: {http_count}")
    print(f"  scrape_method=playwright: {playwright_count}")
    print(f"  verified: {verified}")
    print(f"  unverified: {len(data) - verified}")


if __name__ == "__main__":
    main()
